### ISSUE TITLE
Array of mixins?

### ISSUE THREAD

**Issue by SimonDegraeve** [brigand/react-mixin#1]
I think it would be nice to be able to pass an array of mixins instead of calling multiple time the same function on the same prototype... Any thoughts?

**Comment by brigand** [comment]
I haven't done this, because if you did:

```js
reactMixin(C.prototype, [mixin1, mixin2]);
```

And it gives you the error 'Cannot mixin shouldComponentUpdate because it has a unique constraint', the error stack just reports that one line as the culprit.  The way it is currently, it clearly points the finger at the source of the error.

Aside from that, it also, in my opinion, looks cleaner when using mixin returning functions.

```js
reactMixin(C.prototype, makeMixin1({
  foo: 'bar'
}));
reactMixin(C.prototype, mixin2);
```

Are these non-issues?

**Comment by brigand** [comment]
Closing this, if you really need an array of mixins:

```js
mixins.forEach((mixin) => {
    reactMixin(C, mixin); 
});
```
