### ISSUE TITLE
mixable class.

### ISSUE THREAD

**Issue by Verikon** [brigand/react-mixin#7]
https://gist.github.com/Verikon/c282f2b927944a33e10b

**Comment by brigand** [comment]
Similar things have been brought up before.  The problems:

 - performance: it's deferred to component instantiation time, and must run multiple times (mostly negligible)
 - errors: there's no place for early errors, also because it's deferred to component instantiation time

In this specific code:

 - errors: none, it's fail soft
 - lifecycle: various hooks have special behavior when specified in mixins and the component itself
 - lifecycle: if props change, the mixins aren't updated

Maybe problems, maybe interesting.

 - responsibility: the caller is responsible for providing mixins?

Could you clarify the motivation for the last one?

**Comment by brigand** [comment]
Here's the same api implemented with reactMixin.

```js
const React = require('react');
const reactMixin = require('react-mixin');

class MixableComponent extends React.Component{
    constructor(props){
        super(props);
        if (props.mixins) {
            const mixins = Array.isArray(props.mixins) ? props.mixins : [props.mixins];
            mixins.forEach(mixin => reactMixin(this, mixin));
        }
    }
}
```

**Comment by Verikon** [comment]
I've thrown it on the caller in an understanding that mixins are loosely coupled as opposed to something such as a trait which is intrinsically baked in ( http://php.net/manual/en/language.oop5.traits.php ).

It's also just a gist, so it's a way to take an array of mixins ( see quesy below ) and it feels somewhat elegant in that you can write a component to extend this and mixin something like isDraggable etc for one context, and say isClonable for another.

You can also use the method after insantiation (obvious a mixout method may also be useful therefore).
